name: ventas_b2b
description: Aplicación de ventas B2B con Flutter

# Evita la publicación accidental en pub.dev
publish_to: 'none'

# Considera actualizar tu versión a medida que lanzas nuevas builds
version: 1.0.0+1 # O la versión actual de tu app

# Requisito de SDK para Flutter moderno. Asegúrate que tu Flutter esté actualizado.
environment:
  sdk: '>=3.0.0 <4.0.0' # Compatible con Flutter 3.x

dependencies:
  flutter:
    sdk: flutter

  #----- UI & UX -----
  cupertino_icons: ^1.0.8
  shimmer: ^3.0.0
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.3
  pull_to_refresh: ^2.0.0
  flutter_staggered_grid_view: ^0.7.0
  dropdown_search: ^6.0.2
  cached_network_image: ^3.4.1
  flutter_svg: ^2.1.0
  photo_view: ^0.15.0
  flutter_rating_bar: ^4.0.1

  #----- Firebase -----
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6
  firebase_storage: ^12.4.5
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_crashlytics: ^4.3.5
  # firebase_performance: ^0.10.1+5 # TEMPORALMENTE COMENTADO
  cloud_functions: ^5.4.0

  #----- State Management & Navigation -----
  provider: ^6.1.2
  get: ^4.6.6
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5

  #----- Core Utilities -----
  intl: ^0.20.2
  uuid: ^4.5.1
  collection: ^1.19.1
  path: ^1.9.1
  json_annotation: ^4.9.0

  #----- Local Storage -----
  shared_preferences: ^2.2.3
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.3

  #----- Native Features -----
  image_picker: ^1.1.2
  cross_file: ^0.3.4+2
  mobile_scanner: ^6.0.8
  geolocator: ^14.0.0
  location: ^8.0.0

  #----- Reporting & Documents -----
  pdf: ^3.11.0
  printing: ^5.12.0
  fl_chart: ^0.71.0
  excel: ^4.0.6

  #----- Network & Connectivity -----
  http: ^1.3.0
  dio: ^5.5.0+1
  connectivity_plus: ^6.1.3

  #----- External Integrations -----
  google_sign_in: ^6.2.1
  share_plus: ^10.1.4
  url_launcher: ^6.3.1
  webview_flutter: ^4.11.0
  flutter_email_sender: ^7.0.0

# Fin de la sección dependencies


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Utilizar lints recientes
  build_runner: ^2.4.15
  json_serializable: ^6.9.5
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.4 # Mantenido en downgrade por conflicto excel<->archive
  dependency_validator: ^5.0.2 # Buena herramienta para revisar dependencias


# y causaban conflictos irresolubles con las dependencias principales actualizadas.
# Es ESENCIAL eliminar los overrides para una aplicación robusta y mantenible.

# Configuración específica de Flutter
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    # - assets/icons/
    - assets/images/logo.png

  # Ejemplo de configuración de fuentes (si las usas)
  # fonts:
  #   - family: TuFuente
  #     fonts:
  #       - asset: fonts/TuFuente-Regular.ttf
  #       - asset: fonts/TuFuente-Bold.ttf
  #         weight: 700
